Provinces = {
    "lappland":         {"norr": "", "nordöst": "", "öster": "norrbotten", "sydöst": "västerbotten", "söder": "ångermanland", "sydväst": "jämtland", "väst": "", "nordväst": ""},
    "ångermanland":     {"norr": "lappland", "nordöst": "västerbotten", "öster": "", "sydöst": "", "söder": "medelpad", "sydväst": "", "väst": "jämtland", "nordväst": ""},
    "blekinge":         {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "bohuslän":         {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "dalarna":          {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "dalsland":         {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "gästrikland":      {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "gotland":          {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "halland":          {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "hälsingland":      {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "härjedalen":       {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "jämtland":         {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "medelpad":         {"norr": "ångermanland", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "närke":            {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "norrbotten":       {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "öland":            {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "östergötland":     {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "skåne":            {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "småland":          {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "södermanland":     {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "uppland":          {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "värmland":         {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "västerbotten":     {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "västergötland":    {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
    "västmanland":      {"norr": "", "nordöst": "", "öster": "", "sydöst": "", "söder": "", "sydväst": "", "väst": "", "nordväst": ""},
}